version: '3'

services:
  mysql:
    image: centos/mysql-57-centos7
    expose:
      - 3306
    environment:
      - MYSQL_USER=xcz
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=xczdb

  activiti-base:
    build:
      context: ./activiti-base
      dockerfile: src/docker/Dockerfile
      args:
        JAR_FILE: activiti-base-1.0.0-SNAPSHOT.jar
    image: jenkinxu/activiti-base:1.0.0-SNAPSHOT
    container_name: activiti-demo-base
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 60
      WAIT_HOST_CONNECT_TIMEOUT: 30
