version: '3'

services:
  mysql:
    image: centos/mysql-57-centos7
    expose:
      - 3306
    environment:
      - MYSQL_USER=xcz
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=xczdb

  activiti-base:
    image: jenkinxu/activiti-base:1.0.0-SNAPSHOT
    # depends_no是docker启动顺序而不会等待服务完成，所以可能因为服务依赖而失败
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
